using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace AP8PO
{
    public class GroupViewModel
    {

    }

    /// <summary>
    /// Interaction logic for ManageGroupControl.xaml
    /// </summary>
    public partial class ManageGroupControl : UserControl
    {
        public GroupViewModel ViewModel = new GroupViewModel();

        internal ObservableCollection<Group> Groups { get; set; }

        public ManageGroupControl()
        {
            InitializeComponent();
            DataConnection.DbContext.Groups.Load();
            
            list.ItemsSource = DataConnection.DbContext.Groups.Local;
            list.AutoGeneratedColumns += List_AutoGeneratedColumns;
        }

        private void List_AutoGeneratedColumns(object sender, EventArgs e)
        {
            list.Columns[0].Visibility = Visibility.Hidden;
        }

        private void AddGroupButton_Click(object sender, RoutedEventArgs e)
        {

        }
    }
}
