using System;
using System.Collections.ObjectModel;
using System.Data.Entity;
using System.Windows;
using System.Windows.Controls;
using System.Linq;
using System.Collections.Generic;
using AP8PO.UserControls;

namespace AP8PO
{
    public class GroupViewModel : Model
    {
        public ObservableCollection<Course> Courses;

        public GroupViewModel()
        {
            DataConnection.DbContext.Groups.Load();
            DataConnection.DbContext.Courses.Load();
            Courses = DataConnection.DbContext.Courses.Local;
        }

        public Group CreateNew()
        {
            var group = new Group();
            DataConnection.DbContext.Insert(group);
            return group;
        }

        public void Remove(Group group)
        {
            DataConnection.DbContext.Delete(group);
        }

        public void ConfirmChanges()
        {
            DataConnection.DbContext.SaveChanges();
        }
    }

    /// <summary>
    /// Interaction logic for ManageGroupControl.xaml
    /// </summary>
    public partial class ManageGroupControl : UserControl, ITab
    {
        public GroupViewModel ViewModel = new GroupViewModel();

        public ObservableCollection<Course> AllCourses;
        public ObservableCollection<Group> AllGroups;
        //internal ObservableCollection<Group> Groups { get; set; }

        public ManageGroupControl()
        {        
            InitializeComponent();
            this.DataContext = this;
            DataConnection.DbContext.Courses.Load();
            DataConnection.DbContext.Groups.Load();
            AllCourses = DataConnection.DbContext.Courses.Local;
            AllGroups = DataConnection.DbContext.Groups.Local;
            
            list.ItemsSource = DataConnection.DbContext.Groups.Local;
            list.AutoGeneratedColumns += List_AutoGeneratedColumns;
            list.CellEditEnding += List_CellEditEnding; 
        }

        private void List_CellEditEnding(object sender, DataGridCellEditEndingEventArgs e)
        {
            if(e.Column.Header.ToString() == "StudentsCount") //check if students count column
            {
                var tb = (e.EditingElement as TextBox);
                string text = tb.Text;
                if (Int32.TryParse(text, out int num))
                {
                    if ((list.SelectedItem as Group).StudentsCount != num) //check if value has changed
                    {
                        var group = tb.DataContext as Group;
                        group.StudentsCount = num;

                        try
                        {
                            ManageCommitsControl a = ((Application.Current.MainWindow.Content as Grid).Children[0] as TabControl)
                                .Items.OfType<TabItem>()
                                .Where(o => o.Content.GetType() == typeof(ManageCommitsControl)).FirstOrDefault().Content as ManageCommitsControl;
                            a.GenerateCommits();
                            MessageBox.Show("Because you have changed number of students, commits will be re-generated.");
                        }
                        catch{}

                        
                        
                    }  
                }

            }
        }

        private void List_AutoGeneratedColumns(object sender, EventArgs e)
        {
            list.Columns[0].Visibility = Visibility.Hidden;
            list.Columns[list.Columns.Count-1].Visibility = Visibility.Hidden;
        }

        private void DeleteGroupButton_Click(object sender, RoutedEventArgs e)
        {
            DeleteSelectedRecord();
        }

        private void AssignButtonClick(object sender, RoutedEventArgs e)
        {
            var course = (sender as Button).DataContext as Course;
            var g = (list.SelectedItem as Group);
            if (course.GroupID == g.ID)
                MessageBox.Show($"Course {course.Name} ({course.Abbrevation}) is already assigned to group {g.Name} ({g.Abbrevation})");
            else
            {
                if (course.Group != null)
                {
                    var msgBoxResult = MessageBox.Show($"This course is assigned to group {course.Group} ({course.Group.Abbrevation}). Are you sure you want to change it?","",
                                    MessageBoxButton.YesNo,
                                    MessageBoxImage.Question
                                    );
                    if (msgBoxResult == MessageBoxResult.No)
                        return;
                }

                course.GroupID = g.ID;
                course.Group = g;
                course.Group.ID = g.ID;
                ViewModel.ConfirmChanges();
            }
        }

        private void UnassignButtonClick(object sender, RoutedEventArgs e)
        {
            var course = (sender as Button).DataContext as Course;
            course.GroupID = null;
            course.Group = null;
            ViewModel.ConfirmChanges();
            
        }

        public void AddRecord()
        {
            ViewModel.CreateNew();
        }

        public void DeleteSelectedRecord()
        {
            if (list.SelectedItem is Group)
            {
                Group group = (Group)list.SelectedItem;
                ViewModel.Remove(group);
            }
        }
    }
}
